# see https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Example project

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 180    
    Environment:
      Variables:
        DeploymentStageName: development
Resources:
# Cognito Auth Services API
  ServicesAPIs:
    Type: AWS::Serverless::Api    
    Properties:
      StageName: !Ref DeploymentStageName
      DefinitionBody:
        swagger: 2.0
        info:
          title: Services APIs                            
        paths:
          "/HelloWorldFunction":
            post:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
                responses:
                  default:
                    statusCode: '200'
                passthroughBehavior: when_no_match              
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  schema:
                    "$ref": "#/definitions/Empty"
          "/RobotsFunction":
            post:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RobotsFunction.Arn}/invocations
                responses:
                  default:
                    statusCode: '200'
                passthroughBehavior: when_no_match              
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  schema:
                    "$ref": "#/definitions/Empty"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/helloworld/index.js
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 30 # seconds, 300 max
      Events:
        RestApi:
          Type: Api
          Properties:           
            Path: /{proxy+}
            Method: post
            RestApiId:
                Ref: ServicesAPIs
  RobotsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/robots/index.js
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 30 # seconds, 300 max
      Events:
        RestApi:
          Type: Api
          Properties:           
            Path: /{proxy+}
            Method: ANY
            RestApiId:
                Ref: ServicesAPIs
