swagger: 2.0
info:
    title: Services APIs                            
paths:
    "/HelloWorldFunction":
    post:
        x-amazon-apigateway-integration:
        httpMethod: post
        type: aws_proxy
        uri:
            Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${stageVariables.HelloWorldFunction}/invocations
        responses:
            default:
            statusCode: '200'
        passthroughBehavior: when_no_match              
        produces:
        - application/json
        responses:
        '200':
            description: 200 response
            schema:
            "$ref": "#/definitions/Empty"
    "/RobotsFunction":
    post:
        x-amazon-apigateway-integration:
        httpMethod: post
        type: aws_proxy
        uri:
            Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${stageVariables.RobotsFunction}/invocations
        responses:
            default:
            statusCode: '200'
        passthroughBehavior: when_no_match              
        produces:
        - application/json
        responses:
        '200':
            description: 200 response
            schema:
            "$ref": "#/definitions/Empty"